repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
-   repo: local
    hooks:
    - id: isort
      name: Run isort
      entry: isort
      language: system
      types:
        - python
    - id: black
      name: Run black
      entry: black
      language: system
      types:
        - python
    - id: flake8
      name: Run flake8
      entry: flake8
      language: system
      types:
        - python
